/*
 * This file is generated by jOOQ.
 */
package demo.tree.pojo;


import demo.tree.pojo.tables.DocumentTree;


/**
 * Convenience access to all tables in tree_demo
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>tree_demo.document_tree</code>.
     */
    public static final DocumentTree DOCUMENT_TREE = DocumentTree.DOCUMENT_TREE;
}
