/*
 * This file is generated by jOOQ.
 */
package demo.tree.pojo;


import demo.tree.pojo.tables.DocumentTree;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TreeDemo extends SchemaImpl {

    private static final long serialVersionUID = 396921496;

    /**
     * The reference instance of <code>tree_demo</code>
     */
    public static final TreeDemo TREE_DEMO = new TreeDemo();

    /**
     * The table <code>tree_demo.document_tree</code>.
     */
    public final DocumentTree DOCUMENT_TREE = DocumentTree.DOCUMENT_TREE;

    /**
     * No further instances allowed
     */
    private TreeDemo() {
        super("tree_demo", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            DocumentTree.DOCUMENT_TREE);
    }
}
